export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const GET_SHOWS = 'GET_SHOWS';
export const GET_SHOWS_SUCCESS = 'GET_SHOWS_SUCCESS';
export const GET_SHOWS_FAIL = 'GET_SHOWS_FAIL';

export const GET_SHOW = 'GET_SHOW';
export const GET_SHOW_SUCCESS = 'GET_SHOW_SUCCESS';
export const GET_SHOW_FAIL = 'GET_SHOW_FAIL';

export const FILTER_BY_GENRE = 'FILTER_BY_GENRE';
export const FILTER_BY_LANGUAGE = 'FILTER_BY_LANGUAGE';
export const FILTER_BY_TYPE = 'FILTER_BY_TYPE';

export const SAVE_USER = 'SAVE_USER';
export const SAVE_USER_START = 'SAVE_USER_START';
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';
export const SAVE_USER_FAIL = 'SAVE_USER_FAIL';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';


export const ADD_TO_FAVOURITE = 'ADD_TO_FAVOURITE';
export const REMOVE_FROM_FAVOURITE = 'REMOVE_FROM_FAVOURITE';
export const GET_FAVOURITE = 'GET_FAVOURITE';
export const GET_FAVOURITE_SUCCESS = 'GET_FAVOURITE_SUCCESS';
export const GET_FAVOURITE_FAIL = 'GET_FAVOURITE_FAIL';